// Created with resguy v8 (September 2018)
// https://github.com/wootguy/resguy

de_rex.wad
do_map.wad
gfx/detail/dt_metal1.tga
grid.wad
hs4.wad
ma_quasar.wad
maps/ma_quasar_detail.txt
models/metalarena/minion.mdl
models/metalarena/special.mdl
models/metalarena/weapons/p_as50g.mdl
models/metalarena/weapons/p_ethereal.mdl
models/metalarena/weapons/p_m4a1scope.mdl
models/metalarena/weapons/p_m60e4.mdl
models/metalarena/weapons/p_pila.mdl
models/metalarena/weapons/p_skull1.mdl
models/metalarena/weapons/p_skull5.mdl
models/metalarena/weapons/p_tar21.mdl
models/metalarena/weapons/v_as50g.mdl
models/metalarena/weapons/v_ethereal_mg.mdl
models/metalarena/weapons/v_m4a1scope.mdl
models/metalarena/weapons/v_m60e4_mg.mdl
models/metalarena/weapons/v_pila.mdl
models/metalarena/weapons/v_skull1_mg.mdl
models/metalarena/weapons/v_skull5_mg.mdl
models/metalarena/weapons/v_tar21_mg.mdl
models/metalarena/weapons/w_as50g.mdl
models/metalarena/weapons/w_ethereal.mdl
models/metalarena/weapons/w_m4a1scope.mdl
models/metalarena/weapons/w_m60e4.mdl
models/metalarena/weapons/w_pila.mdl
models/metalarena/weapons/w_skull1.mdl
models/metalarena/weapons/w_skull5.mdl
models/metalarena/weapons/w_tar21.mdl
models/player/ma_alice_blue/ma_alice_blue.mdl
models/player/ma_alice_red/ma_alice_red.mdl
models/player/ma_rifleman_blue/ma_rifleman_blue.mdl
models/player/ma_rifleman_red/ma_rifleman_red.mdl
models/player/ma_tanker_blue/ma_tanker_blue.mdl
models/player/ma_tanker_red/ma_tanker_red.mdl
sound/metalarena/null.wav
sound/metalarena/supply.wav
sound/metalarena/zbs_death_1.wav
sound/weapons/as50-1.wav
sound/weapons/as50_clipin1.wav
sound/weapons/as50_clipin2.wav
sound/weapons/as50_clipout1.wav
sound/weapons/as50_clipout2.wav
sound/weapons/as50_draw.wav
sound/weapons/chainsaw_draw.wav
sound/weapons/chainsaw_draw1.wav
sound/weapons/chainsaw_hit1.wav
sound/weapons/chainsaw_idle.wav
sound/weapons/chainsaw_slash1.wav
sound/weapons/ethereal-1.wav
sound/weapons/ethereal_draw.wav
sound/weapons/ethereal_reload.wav
sound/weapons/m4a1_boltpull.wav
sound/weapons/m4a1_clipin.wav
sound/weapons/m4a1_clipout.wav
sound/weapons/m4a1_deploy.wav
sound/weapons/m4a1_unsil-1.wav
sound/weapons/m60e4_clipin1.wav
sound/weapons/m60e4_clipin2.wav
sound/weapons/m60e4_clipin3.wav
sound/weapons/m60e4_clipin4.wav
sound/weapons/m60e4_clipout1.wav
sound/weapons/m60e4_clipout2.wav
sound/weapons/m60e4_shoot1.wav
sound/weapons/skull1.wav
sound/weapons/skull1_clipin.wav
sound/weapons/skull1_clipout.wav
sound/weapons/skull1_draw.wav
sound/weapons/skull5-1.wav
sound/weapons/skull5_boltpull.wav
sound/weapons/skull5_clipin.wav
sound/weapons/skull5_clipout.wav
sound/weapons/skull5_draw.wav
sprites/wpn/weapon_as50g.txt
sprites/wpn/weapon_ethereal.txt
sprites/wpn/weapon_m4a1scope.txt
sprites/wpn/weapon_m60.txt
sprites/wpn/weapon_pila.txt
sprites/wpn/weapon_skull1.txt
sprites/wpn/weapon_skull5.txt
sprites/wpn/weapon_tar21.txt
sprites/wpnhud/ch_sniper.spr
sprites/wpnhud/crosshairs.spr
sprites/wpnhuds/640hud21.spr
sprites/wpnhuds/640hud60.spr
sprites/wpnhuds/640hud7.spr
sprites/wpnhuds/640hud84.spr
sprites/wpnhuds/weapon_ethereal.spr
sprites/wpnhuds/weapon_m4a1scope.spr
sprites/wpnhuds/weapon_m60e.spr
sprites/wpnhuds/weapon_skull1.spr
sprites/wpnhuds/weapon_skull5.spr
sprites/wpnhuds/weapon_tar21.spr
